### ISSUE TITLE
Throughput Criterion is Skewed

### ISSUE THREAD

**Issue by carlwitt** [cooperative-computing-lab/efficient-resource-allocations#1]
Well done paper and implementation, thanks for sharing. I think there are three debatable choices on the throughput criterion, and I'd be interested in your opinion.

1) Jobs per second is not interpretable
I've been experimenting with measuring throughput in workflow execution simulations and found that the jobs per second metric is really not a good choice, because the amount of work per job can vary so much. Although its an appealingly simple metric, its barely interpretable because 1 job per second can be anything from a lot to catastrophic performance. In contrast, I found area per second, the product of used resources and time quite useful, e.g., memory throughput is 1 TB.

2) Failed first attempts are not parallelized
At the moment, each failed attempt adds its run time to the total time. However, this assumes that only one failing attempt can run at a time, although there is no reason why all resources should be blocked. I corrected for this below by parallelizing failing first attempts too, effectively dividing the run time by the fraction of available resources allocated to the attempt.

3) The calculation makes implicit assumptions about the frequency of small and large jobs
The way throughput is calculated currently, it is assumed that the number of small jobs is larger than the number of big jobs, because for parallelization it is assumed that the available resources can be fully utilized by parallel instances of a jobs. However, if there are not enough small jobs, the parallelization is restricted too. Even in the limit, the relative frequencies of different sized jobs matter. I played around with a version that assumes equal task frequencies and one that uses the original assumption that there are exactly as many small jobs to fill the resource capacity (I refer to it as inversely proportional task frequencies).

I've seen the original throughput criterion occasionally make weird decisions, however, with these corrections applied, it gives pretty much the same results as the wastage criterion (which are good).
I think this makes sense, since when we're allowed to squeeze and reshape all the allocations, we entirely avoid external fragmentation, which seems important for throughput. 

```python
def throughput_witt(self, allocation, task_frequencies: str = "inverse"):
    maximum = float(self.maximum_seen)

    work = 0
    total_time = 0

    for i in range(0,len(self.values)):
        v = self.values[i]
        t = self.times[i]

        # the number or absolute frequency of tasks plays an important role
        # to fully exploit parallelism on small tasks, we need many of them!
        # Tovar's throughput estimator assumes there are many more small tasks than large tasks.
        # This is what we use here, too. We assume that each task occurs so often that it could fill a resource of capacity equal to the maximum seen.
        # This is called "inversely proportional" because the biggest task is assumed to be present in the workload mix only once.
        # Alternatively, we may assume that all tasks appear with equal frequency.
        num_tasks_each = maximum / v if task_frequencies == "inverse" else 1

        # Eventually, the work contributed by a task always equals its resource usage times its runtime
        work += num_tasks_each * v*t

        # the time to complete depends on over- and undersizing
        # calculate time according to allocation=reservation*time/capacity
        # this implies moldable tasks that can be perfectly fit into available area (resource capacity * time).
        # this is a simplification that might be justified by the steady state argument, and otherwise corresponds to an upper bound on throughput
        if v <= allocation:
            # all successful attempts COULD run completely parallel, if no oversizing wastage was present.
            # for inverse and allocation = v we have total_time += max/v * v * t / max = t
            # with oversizing, we reduce throughput because the area (allocation*t) needed to complete is larger than v*t
            total_time += num_tasks_each * allocation * t / maximum
        else:
            # the first attempts can be parallelized according to allocation size.
            first_attempts = num_tasks_each * allocation * t / maximum
            # the actual work then happens in a maximum size allocation, which forces sequential execution
            total_time += first_attempts + num_tasks_each * t

    return work/total_time
```

**Comment by btovar** [comment]
Carl,

Thanks! I'll check the code next Monday. But for now I'll answer in order:

1. As you say, this seems to compare more to our min waster computation. Next time I'm in the office I'll try to optimize the equations using resource throughput to see if we get the same result. That said, in practice we have seen that different criteria tend to generate about the same first allocations. (I.e., min waste and max throughput differ only in a small parameter region.) Do you have some examples where you get different allocations? That is always interesting to see.

2. If I understand correctly, you are using the maximum seen to pack as many tasks in a maximum allocation. That makes total sense from a practical perspective, and it is specially useful when your nodes are much bigger than your biggest task. So, as long as the first task that gives you a maximum_seen is rerun using the whole maximum allocation it should be ok. We did not include this in the paper because it is much harder to prove any guarantees, although we have use that in practice when we allow more than 1 retry per task.

3. There is not such assumption. It is simply that if you have more large tasks than small tasks, the scheme will find that retries are not beneficial. However, it will still generate the correct answer according to the model, that is, run all tasks using the maximum allocation. (In such distributions using  maximum_seen instead may be quite advantageous.) We tried to build the model so that we did not make any assumptions about the probability distributions of tasks.

Best wishes!

Ben

**Comment by carlwitt** [comment]
Yes, I can share some examples, I'll check back when I'm in the office again on Monday.

Cheers,
Carl

**Comment by carlwitt** [comment]
Hi Ben,

here's an example where the throughput criterion allocates very little resources. 
```
first allocation (throughput) 1
first allocation (waste) 160
first allocation (fixed = maximum resource usage across all tasks) 360
```
I plotted the objective functions for my modified throughput criterion, which has a similar problem when assuming inverse task frequencies. For uniform task frequencies, it peaks around your wastage criterion (160). The green line shows the unmodified throughput criterion. 
Interestingly, when dividing all resource usages and run times by ten, the problem goes away.

![uniform-vs-inverse](https://user-images.githubusercontent.com/956383/53726421-34858100-3e6e-11e9-9b02-2f58b635d3da.png)
Sorry for the missing axis labels, the x-axis shows the first allocation (which the argmax runs over), and the y-axis shows the throughput.

Here's the data, I used `rss` as the resource usage and `run_time`.
[20040-3.csv.gz](https://github.com/cooperative-computing-lab/efficient-resource-allocations/files/2925873/20040-3.csv.gz)

**Comment by btovar** [comment]
Thanks Carl, I'll check it out.

Note that allocating very little resources is not incorrect by itself. It may still give you the best overall job throughput. That said, it may be that job throughput is not the criterion every application may want to optimize. With that, I think we can divide the discussion in two parts:

1) Whether the model has an error for the allocations generated when optimizing job throughput.
2) Whether it makes no sense to optimize job throughput in general, and better focus on min waste/max resource throughput.

I think your arguments are with regards to 2, correct? If so, we can work on turning your function throughtput_witt in something like the function __first_allocation_by_waste. One immediate change is that throughtput_witt cannot make any assumptions with regards to the task distribution (i.e., no inverse parameter), as all the task sizes frequencies should be collected online. Otherwise, the comparison with task_frequencies == inverse has an unfair advantage/disadvantage, as it may guess correctly/incorrectly the input distribution.

**Comment by btovar** [comment]
To add, it seems that the less tasks you have, the more maximizing throughput looks weird. Minimizing waste (or in your case, maximizing resource throughput) seems more stable with regards to the number of tasks. I think this is simply because the min-waste expression simply accumulates, and does not have a denominator, as the job throughput does.

**Comment by btovar** [comment]
Regarding the code:
```python
 # the number or absolute frequency of tasks plays an important role
 # to fully exploit parallelism on small tasks, we need many of them!
 # Tovar's throughput estimator assumes there are many more small tasks than large tasks.
```
As I mentioned, we make no such assumption. It is just that first allocations make much more sense when you have many small tasks as compared to large tasks.

```python
 # This is what we use here, too. We assume that each task occurs so often that it could fill a resource of capacity equal to the maximum seen.
 # This is called "inversely proportional" because the biggest task is assumed to be present in the workload mix only once.
 # Alternatively, we may assume that all tasks appear with equal frequency.
        num_tasks_each = maximum / v if task_frequencies == "inverse" else 1
```
The problem here is that the frequency of tasks is being fed to the function, rather than computed from the available data. The throughput computed will not correspond to the one found using fa.first_allocation(...). (That said, you can always brute-force it, as in the graphs you show.) Similarly:

```python
 total_time += first_attempts + num_tasks_each * t
```

does runs failed attempts in parallel. However, note that you can't do that without knowing apriori how big the task is (that is, without the oracle that tells you task_frequencies == inverse).

fa.throughput() is a little weird in that while it 'knows' the resources the task finally used, it does the computation as simulating how the tasks would be run (i.e., first with the first allocation, then with max resources.)

**Comment by carlwitt** [comment]
Hi Ben,

division of discussion is a good idea. Maybe I can add 3) the inverse job frequencies assumption, which I do think is made:  Consider three jobs with (resource usage, run time) = (1, 10), (2, 10), (10, 10) a first allocation of a_1 = 1 and a maximum allocation of a_m = 10.
Using the first version of Equation 3, the throughput is calculated as

![latex-image-1](https://user-images.githubusercontent.com/956383/53813327-ac7ea480-3f5d-11e9-95c3-79ec6ea3ef85.png)

Which assumes that during 50 time units 12 jobs finish, 10 of the smallest type, and 1 each of the other sizes. Sketching this out:
![screen shot 2019-03-05 at 15 54 41](https://user-images.githubusercontent.com/956383/53813969-0cc21600-3f5f-11e9-98e3-918cdb3a5fea.png)

Maybe this illustrates a bit better what I meant with non-parallel failed first attempts and the task frequencies. Here throughput depends a lot on job frequencies. Best throughput (fixing a_1 and a_m) is 1/3 for 8x(1,10) 1x(2,10) 1x(10,10), which packs nicely. 
![screen shot 2019-03-05 at 15 58 16](https://user-images.githubusercontent.com/956383/53814222-80fcb980-3f5f-11e9-8891-6adbe5e7e4bd.png)

**Comment by btovar** [comment]
Carl,

Interesting stuff! Thank you for the discussion.

In reaching 0.24 you had to use that p =1/3 was true for each type of task. Thus, the inverse size assumption was not made. (Also, in that example the optimal first allocation seems to be 10, that is, no retries. Any value less than 1 indicates the retries hurt you.)

However, it is true that smaller tasks have a better chance to succeed. This may only temporarily change the distribution of tasks that **have** succeeded, but not the **overall** input distribution. The two distributions will be the same if no task is ever retried, or when all tasks have been completed. Again, note that no assumption is being made, but it is a consequence of applying the strategy.

I think that the inverse size distribution idea is answering another question: for which distributions is a retry strategy particularly advantageous?  Note that in the paper when we say 'maximize throughput' we do not mean the universally best throughput, but the best throughput given our policy of retries.
